spring.application.name=voiceguard

spring.datasource.url=jdbc:mysql://localhost:3306/voiceguard
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:07!@SraSadaf31}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect